name: EthicML CI

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'docs/**'
    - 'docsource/**'
    - 'examples/**'
    - '**/*.md'
    - .gitignore
    - CODEOWNERS
    - LICENSE
    - make_release.sh

jobs:

  lint_with_pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint with pylint
      run: |
        python run_pylint.py
        python run_pylint_tests.py

  format_with_black_and_isort:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    - name: Format with black
      run: |
        python -m black --check -l 100 -t py37 -S ethicml/
        python -m black --check -l 100 -t py37 -S tests/
    - name: Format with isort
      run: |
        isort . --check --diff

  type_check_with_mypy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install git+https://github.com/predictive-analytics-lab/python-type-stubs.git
        pip install typed-argument-parser==1.4 teext numpy>=1.20.1 palkit
    - name: Type check with mypy
      run: |
        python run_mypy.py
        python run_mypy_tests.py

  check_docstrings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pydocstyle
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle
    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle --count -e ethicml

  test_with_pytest:
    needs: [lint_with_pylint, format_with_black_and_isort, type_check_with_mypy, check_docstrings]
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #  ---  check-out repo and set-up python ---
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Set up Poetry cache for Python dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venvEM-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install -E ci --no-interaction --no-root

      #----------------------------------------------
      #  -----           Run Tests          -----
      #----------------------------------------------
      - name: Test with pytest
        run: |
          poetry run python -m pytest -vv --cov=ethicml --cov-fail-under=80  tests/
